source 'https://cdn.cocoapods.org/'
use_frameworks!
inhibit_all_warnings!

platform :ios, '15.0'

target 'Rudder-Braze_Example' do
  pod 'Rudder-Braze', :path => '../'
  pod 'BrazeUI', '>= 15.0.0', '< 19.0.0' # Used to enable Braze IAM (In-App Message)

  target 'Rudder-Braze_Tests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  # Xcode 26+ refuses deployment targets below iOS 15
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
