source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
inhibit_all_warnings!

platform :ios, '11.0'

target 'Rudder-Braze_Example' do
  pod 'Rudder-Braze', :path => '../'
  pod 'BrazeUI' # Used to enable Braze IAM (In App Messaging)
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        xcconfig_path = config.base_configuration_reference.real_path
        xcconfig = File.read(xcconfig_path)
        xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
        File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
      end
    end
  end
end
