name: Code Quality Checks
on:
  pull_request:
    branches: ['master']
    types: ['opened', 'reopened', 'synchronize']

jobs:
  build:
    name: Code Quality Checks
    runs-on: macOS-latest
    
    steps:
      - name: Checkout source branch
        uses: actions/checkout@v3
        
      # I observed that the `Execute pod lint` step is failing and the setting up the XCode to 15.4 seems to solve the issue.
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4'

      - name: Install Cocoapods
        run: gem install cocoapods
      
      - name: Execute pod lint
        run: pod lib lint --no-clean --allow-warnings
